[theme]
base = "light"
primaryColor = "#a12732"
backgroundColor = "#f5f0e5"
secondaryBackgroundColor = "#eee8da"
textColor = "#18324f"
font = "sans serif"

[server]
folderWatchBlacklist = [".models", ".venv"]
